### ISSUE TITLE
Controlling Speed of Shooter

### ISSUE THREAD

**Issue by Ouroboroz** [Team2554/Sloth#5]
Problem: The shooter wheels spin at inaccurate and nonconstant speeds, especially after a long time of use.

Possible Solutions:
- [ ] Bind a button and the right analog stick on the controller to modify the speed of the shooter.
    - The button has to be pressed and the analog stick has to be above a dead zone to modify the speed
    - The analog stick will allow the user to increase and decrease the shooter speed by a slight amount
- [ ] Set up Encoder to monitor and actively change the output to keep the speed constant
    - Test for the PID values

**Comment by Ouroboroz** [comment]
This is probably the least important of all the issues. If there is no time to finish this then just set it at  a single speed and pray to god that it doesn't change much as voltage drops.
- [ ] Test for correct shooting speed

**Comment by sriRacha21** [comment]
We're removing the shooter
