### ISSUE TITLE
Exception Called During Creation of Autonomous Commands

### ISSUE THREAD

**Issue by Ouroboroz** [Team2554/Sloth#6]
Problem: Exception is thrown when trying to create Autonomous command objects.

Explanation: Since the drivetrain is not a subsystem, it is instantiated in `roboInit()`. The `RobotDrive` object is not static because it is referenced within instance methods so when the same ports are called again to create a new `RobotDrive` object in autonomous commands, it throws an exception.

Solution:
- [x] Modify the autonomous command constructor so it takes a `RobotDrive` parameter
- [x] When constructing a new autonomous command, make actual parameter as the `RobotDrive` object in `Robot.java`

**Comment by sriRacha21** [comment]
mmm when I got here it looked like it didn't throw an exception, i'll just call this resolved for now

**Comment by Ouroboroz** [comment]
I have fixed this.
