### ISSUE TITLE
Gyro Calibrates in Auto and TeleOp Init

### ISSUE THREAD

**Issue by Ouroboroz** [Team2554/Sloth#9]
Problem: `gyro.calibrate()` is called twice: during `autonomousInit()` and `teleopInit()`

Explanation: During manual testing, there are no FMS so it is not possible to call both `autonomousInit()` and `teleopPeriodic()` in one session. Thus `gyro.calibrate()` is called during `teleopInit()` to make the gyro work during teleop.

Solution:
- [x] Delete the `gyro.calibrate()` line from `teleopInit()`

**Comment by sriRacha21** [comment]
well that was easy
